import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-film-production-tax-incentive-recovery",
  "engine": "recovery",
  "title": "Film Production Tax Incentive Recovery",
  "shortTitle": "Film Production Tax Incentive Recovery",
  "tagline": "Calculate and document jurisdictional film incentives from qualified local labor and production expenditure.",
  "industry": "Media Tax Incentives",
  "buyer": "Film studios, producers, and production finance teams",
  "uiPort": 4739,
  "apiPort": 5739,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Film Production Tax Incentive Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash in one accountable workflow. Calculate and document jurisdictional film incentives from qualified local labor and production expenditure.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Film Production Tax Incentive Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("jurisdiction-incentive-library","FPT01","Jurisdiction incentive library","Execute jurisdiction incentive library using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed jurisdiction incentive library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Jurisdiction incentive library Reference","text","FPT01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("production-entity-registry","FPT02","Production entity registry","Execute production entity registry using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed production entity registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Production entity registry Reference","text","FPT02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("budget-cost-ingestion","FPT03","Budget cost ingestion","Execute budget cost ingestion using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed budget cost ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Budget cost ingestion Reference","text","FPT03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("payroll-residency-validation","FPT04","Payroll residency validation","Execute payroll residency validation using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed payroll residency validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Payroll residency validation Reference","text","FPT04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("vendor-location-validation","FPT05","Vendor location validation","Execute vendor location validation using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed vendor location validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Vendor location validation Reference","text","FPT05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("qualified-spend-classification","FPT06","Qualified spend classification","Execute qualified spend classification using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed qualified spend classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Qualified spend classification Reference","text","FPT06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("related-party-control","FPT07","Related-party control","Execute related-party control using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed related-party control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Related-party control Reference","text","FPT07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("financing-source-treatment","FPT08","Financing source treatment","Execute financing source treatment using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed financing source treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Financing source treatment Reference","text","FPT08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("minimum-spend-threshold","FPT09","Minimum spend threshold","Execute minimum spend threshold using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed minimum spend threshold decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Minimum spend threshold Reference","text","FPT09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("credit-rebate-calculation","FPT10","Credit rebate calculation","Execute credit rebate calculation using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed credit rebate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Credit rebate calculation Reference","text","FPT10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("audit-sample-workbench","FPT11","Audit sample workbench","Execute audit sample workbench using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed audit sample workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Audit sample workbench Reference","text","FPT11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("application-package","FPT12","Application package","Execute application package using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed application package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Application package Reference","text","FPT12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("certificate-tracking","FPT13","Certificate tracking","Execute certificate tracking using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed certificate tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Certificate tracking Reference","text","FPT13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("credit-transfer-monetization","FPT14","Credit transfer monetization","Execute credit transfer monetization using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed credit transfer monetization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Credit transfer monetization Reference","text","FPT14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]}),
feature("production-jurisdiction-analytics","FPT15","Production jurisdiction analytics","Execute production jurisdiction analytics using incentive rules, budgets, payroll, vendors, residency, qualified spend, financing, audits, applications, certificates, transfers, and cash.","Produce a governed production jurisdiction analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Production / Jurisdiction","text","Production / Jurisdiction · Standard Case"],["caseReference","Production jurisdiction analytics Reference","text","FPT15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1827500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2211275],["domainDriver","Incentive Form","select","Refundable credit",["Refundable credit","Transferable credit","Cash rebate"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Jurisdiction incentive library case","Production entity registry case","Budget cost ingestion case","Payroll residency validation case","Vendor location validation case"]})
]);
